In [ ]:
# Arrays Indexing (NumPy Indexing and Slicing)

In [1]:
import numpy as np

In [2]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [4]:
arr[6], arr[9]

(np.int64(17), np.int64(20))

In [6]:
arr[1:4]

array([12, 13, 14])

In [9]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [10]:
arr[3:2:1]

array([], dtype=int64)

In [13]:
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
# NumPy Indexing and Slicing of Matrix

In [15]:
arr = np.arange(1,31).reshape(5, 6)
arr

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30]])

In [16]:
arr[0]

array([1, 2, 3, 4, 5, 6])

In [17]:
arr[0,0]

np.int64(1)

In [19]:
arr[0,4]

np.int64(5)

In [20]:
arr[0][1]

np.int64(2)

In [22]:
slice = arr[0:2, 1:3]
slice

array([[2, 3],
       [8, 9]])

In [23]:
arr[2:6, 4:6]

array([[17, 18],
       [23, 24],
       [29, 30]])

In [24]:
arr[:,2]

array([ 3,  9, 15, 21, 27])

In [ ]:
# Boolean Indexing

In [26]:
arr = np.arange(11, 21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [29]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [30]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])