In [ ]:
# Array Operations

In [3]:
import numpy as np

In [16]:
a1 = np.array([1, 2, 3, 4, 5])
a2 = np.array([6, 7, 8, 9, 10])

In [18]:
sum = a1 + a2
sum

array([ 7,  9, 11, 13, 15])

In [19]:
diff = a2 - a1
diff

array([5, 5, 5, 5, 5])

In [20]:
product = a1 * a2
product

array([ 6, 14, 24, 36, 50])

In [21]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [22]:
a1 // a2

array([0, 0, 0, 0, 0])

In [23]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [25]:
arr = np.array([1, 2, 3, 4, 5])

In [26]:
arr + 10

array([11, 12, 13, 14, 15])

In [29]:
arr2 = np.arange(1, 26).reshape(5, 5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [30]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [ ]:
# Deep and Shallow Copy

In [31]:
a = np.arange(1, 21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [35]:
slice = a[: 5]
slice * 10
slice

array([1, 2, 3, 4, 5])

In [36]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [37]:
a[4 : 7] * 10
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [39]:
a
b = a
b[0] = 99
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
b = a.copy()
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [43]:
b[0] = 1
b

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [44]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [ ]:
# Matrix Operations

In [46]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

In [47]:
A

array([[1, 2],
       [3, 4]])

In [48]:
B

array([[5, 6],
       [7, 8]])

In [49]:
A * B  # Index Multiplication

array([[ 5, 12],
       [21, 32]])

In [50]:
A@B  # Matrix Multiplication

array([[19, 22],
       [43, 50]])

In [51]:
np.dot(A, B)

array([[19, 22],
       [43, 50]])

In [52]:
A.T

array([[1, 3],
       [2, 4]])

In [ ]:
# Stacking Array

In [53]:
A

array([[1, 2],
       [3, 4]])

In [54]:
B

array([[5, 6],
       [7, 8]])

In [55]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])

In [56]:
np.vstack((a, b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [57]:
np.hstack((a, b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [58]:
np.column_stack((a, b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [ ]:
# Splitting Arrays

In [60]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [61]:
np.hsplit(c, 2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [63]:
a = np.vsplit(c, 4)

In [64]:
for i in a:
    print(i)

[[0 1 2 3]]
[[4 5 6 7]]
[[ 8  9 10 11]]
[[12 13 14 15]]
