In [4]:
import numpy as np

Valid Sudoku

In [18]:
s = np.array([
    [5, 3, 4, 6, 7, 8, 9, 1, 2],
    [6, 7, 2, 1, 9, 5, 3, 4, 8],
    [1, 9, 8, 3, 4, 2, 5, 6, 7],
    
    [8, 5, 9, 7, 6, 1, 4, 2, 3],
    [4, 2, 6, 8, 5, 3, 7, 9, 1],
    [7, 1, 3, 9, 2, 4, 8, 5, 6],
    
    [9, 6, 1, 5, 3, 7, 2, 8, 4],
    [2, 8, 7, 4, 1, 9, 6, 3, 5],
    [3, 4, 5, 2, 8, 6, 1, 7, 9]
])
s

array([[5, 3, 4, 6, 7, 8, 9, 1, 2],
       [6, 7, 2, 1, 9, 5, 3, 4, 8],
       [1, 9, 8, 3, 4, 2, 5, 6, 7],
       [8, 5, 9, 7, 6, 1, 4, 2, 3],
       [4, 2, 6, 8, 5, 3, 7, 9, 1],
       [7, 1, 3, 9, 2, 4, 8, 5, 6],
       [9, 6, 1, 5, 3, 7, 2, 8, 4],
       [2, 8, 7, 4, 1, 9, 6, 3, 5],
       [3, 4, 5, 2, 8, 6, 1, 7, 9]])

In [28]:
valid = True

# Check rows
for row in s:
    if np.sum(row) != 45 or len(np.unique(row)) != 9:
        valid = False
        break

# Check columns
if valid:
    for col in s.T:
        if np.sum(col) != 45 or len(np.unique(col)) != 9:
            valid = False
            break

# Check 3x3 boxes
if valid:
    for i in range(0, 9, 3):
        for j in range(0, 9, 3):
            box = s[i:i+3, j:j+3].flatten()

            if np.sum(box) != 45 or len(np.unique(box)) != 9:
                valid = False
                break

if valid:
    print("Valid Sudoku")
else:
    print("Invalid Sudoku")

Valid Sudoku


General Quetions

In [133]:
# Columns: [Age, Math Marks, Science Marks]
data = np.array([
    [18, 85, 78],   # Student 1
    [19, 92, 88],   # Student 2
    [17, 76, 95],   # Student 3
    [18, 65, 70],   # Student 4
    [20, 90, 85]    # Student 5
])

In [134]:
#Get the shape of the matrix.

In [135]:
data.shape

(5, 3)

In [136]:
#Find the average age of students.

In [137]:
np.mean(data[:,0])

np.float64(18.4)

In [138]:
#Extract Math marks of all students.

In [139]:
data[:, 1]

array([85, 92, 76, 65, 90])

In [140]:
#Find the highest Science mark.

In [141]:
np.max(data[:, 2])

np.int64(95)

In [142]:
#Get details of the student who scored more than 90 in Math.

In [143]:
data[data[:, 1] > 90]

array([[19, 92, 88]])

In [144]:
#Increase Math marks of all students by 5.

In [145]:
data[:, 1] += 5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70, 70],
       [20, 95, 85]])

In [146]:
#Find how many students are younger than 19.

In [147]:
len(data[data[:, 0] < 19])

3

In [148]:
#Calculate the average marks in each subject (column-wise mean).

In [149]:
np.mean(data[:, 1:], axis = 0)

array([86.6, 83.2])

In [150]:
#Get data of students who scored at least 80 in both subjects.

In [151]:
data[(data[:, 1] >= 80) & (data[:, 2] >= 80)]

array([[19, 97, 88],
       [17, 81, 95],
       [20, 95, 85]])

In [152]:
#Replace all Science marks < 75 with 0.

In [153]:
data[:, 2][data[:, 2] < 75] = 0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 95],
       [18, 70,  0],
       [20, 95, 85]])