In [1]:
import numpy as np

In [4]:
arr = np.array([1,2,3,4])
arr 

array([1, 2, 3, 4])

In [7]:
a = [1, 3, 4, 5, 2.4]
a

[1, 3, 4, 5, 2.4]

In [8]:
np.array(a)

array([1. , 3. , 4. , 5. , 2.4])

In [10]:
l = [[1,2,3], [4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [11]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
arr1 = np.arange(1, 11, 2)
arr1

array([1, 3, 5, 7, 9])

In [18]:
b = np.zeros((6, 6))
b

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [21]:
arr = np.ones(5)
arr

array([1., 1., 1., 1., 1.])

In [22]:
arr = np.ones((3,8))
arr

array([[1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1.]])

In [35]:
arr = np.linspace(1, 10
                  , 1)
arr

array([1.])

In [ ]:
# Random Generation Function

In [36]:
np.random.rand(5)

array([0.52208912, 0.96902127, 0.12238439, 0.08039354, 0.385759  ])

In [39]:
np.random.randn(20)

array([-2.41322503, -0.56219528, -0.05019615, -1.59849183, -0.28827383,
       -1.22014979, -0.3009955 , -0.73955408,  0.29200726,  0.68262196,
       -0.57109446, -0.79411081, -0.05734362,  1.1883245 ,  1.38138256,
        1.1704996 , -0.06486003,  0.62881498,  1.10389351, -1.583574  ])

In [46]:
np.random.randint(1, 20)

7

In [ ]:
# Arrays Attributes

In [47]:
arr = np.array([[1,2,3], [4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [49]:
arr.shape

(3, 3)

In [50]:
arr.size

9

In [51]:
arr.dtype

dtype('int64')

In [ ]:
# Array Methods

In [52]:
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [54]:
arr.min()

np.int64(1)

In [59]:
arr.max()

np.int64(9)

In [60]:
arr.sum()

np.int64(45)

In [61]:
np.sum(arr, axis = 1)

array([ 6, 15, 24])

In [62]:
np.sum(arr, axis = 0)

array([12, 15, 18])

In [63]:
arr.mean()

np.float64(5.0)

In [64]:
arr.std()

np.float64(2.581988897471611)

In [65]:
arr.argmax()

np.int64(8)

In [66]:
arr.argmin()

np.int64(0)

In [ ]:
# Reshaping and Resizing

In [68]:
arr = np.arange(1, 31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [83]:
new_arr = arr.reshape(3, 10)
new_arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30]])

In [84]:
arr.resize(4, 10, refcheck = False)
arr

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27, 28, 29, 30],
       [ 0,  0,  0,  0,  0,  0,  0,  0,  0,  0]])